AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TrailName:
    Type: String
    Default: 'TestTrail'
  BucketName:
    Type: String
    Default: 'test9125'

Resources:
  CWLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: "cloudTrailLog"
      RetentionInDays: 30

  CWLogRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "CWRoleForCloudTrail"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AWSCloudTrailCreateLogStream
              Effect: Allow
              Action:
              - logs:CreateLogStream
              Resource:
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
            - Sid: AWSCloudTrailPutLogEvents20141101
              Effect: Allow
              Action:
              - logs:PutLogEvents
              Resource:
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'

  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Ref TrailName
      S3BucketName: !Ref BucketName
      IsLogging: true
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      CloudWatchLogsLogGroupArn: !GetAtt CWLogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt CWLogRole.Arn